// Every edit on the site. Media files live in media/{posters,previews,full}/<slug>.*
// and are generated by tools/transcode.py. `featured` clips also appear on the
// pinned timeline strip, in this order.
export const CATEGORIES = {
  brand: "Brand & Food",
  comedy: "Stand-up & Improv",
  story: "Animated Stories",
  creator: "Creator & Events",
};

export const CLIPS = [
  { slug: "tonino-02", title: "Tonino's Pizzeria · 02", cat: "brand", dur: 22.0, featured: true },
  { slug: "herds-of-comedy-01", title: "Herds of Comedy · set 1", cat: "comedy", dur: 104.6, featured: true },
  { slug: "dodo", title: "The last Dodo", cat: "story", dur: 58.7, featured: true },
  { slug: "bodylines-jeep", title: "Bodylines × Jeep", cat: "brand", dur: 30.2, featured: true },
  { slug: "ran-from-the-scene", title: "Ran from the scene", cat: "brand", dur: 14.6, featured: true },
  { slug: "titanic", title: "Titanic, retold", cat: "story", dur: 69.4, featured: true },
  { slug: "improv-01", title: "Improv night · 01", cat: "comedy", dur: 86.7, featured: true },
  { slug: "honey-optimization", title: "Take honey, for example", cat: "creator", dur: 31.6, featured: true },
  { slug: "dinosaur", title: "Dinosaurs, up close", cat: "story", dur: 46.1, featured: true },
  { slug: "wedding-night", title: "Wedding night", cat: "creator", dur: 34.2, featured: true },

  { slug: "tonino-01", title: "Tonino's Pizzeria · 01", cat: "brand", dur: 23.1 },
  { slug: "tonino-03", title: "Tonino's Pizzeria · 03", cat: "brand", dur: 18.2 },
  { slug: "tonino-04", title: "Tonino's Pizzeria · 04", cat: "brand", dur: 21.8 },
  { slug: "tonino-05", title: "Tonino's Pizzeria · 05", cat: "brand", dur: 20.6 },
  { slug: "tonino-06", title: "Tonino's Pizzeria · 06", cat: "brand", dur: 25.5 },
  { slug: "garage-hook-a", title: "Garage hook · cut A", cat: "brand", dur: 21.2 },
  { slug: "garage-hook-b", title: "Garage hook · cut B", cat: "brand", dur: 21.2 },
  { slug: "herds-of-comedy-02", title: "Herds of Comedy · set 2", cat: "comedy", dur: 202.0 },
  { slug: "improv-02", title: "Improv night · 02", cat: "comedy", dur: 55.5 },
  { slug: "improv-03", title: "Improv night · 03", cat: "comedy", dur: 79.6 },
  { slug: "bdelloid", title: "Bdelloid rotifers", cat: "story", dur: 62.6 },
  { slug: "xray", title: "The first X-ray", cat: "story", dur: 40.8 },
  { slug: "documentary-sample", title: "Documentary sample", cat: "story", dur: 38.8, landscape: true },
  { slug: "creator-intro", title: "Creator intro", cat: "creator", dur: 22.6 },
];

export const media = (slug) => ({
  poster: `media/posters/${slug}.webp`,
  preview: `media/previews/${slug}.mp4`,
  full: `media/full/${slug}.mp4`,
});

// 25 fps timecode, the way an NLE shows it: HH:MM:SS:FF
export function timecode(seconds, fps = 25) {
  const f = Math.floor((seconds % 1) * fps);
  const s = Math.floor(seconds);
  const pad = (n) => String(n).padStart(2, "0");
  return `${pad(Math.floor(s / 3600))}:${pad(Math.floor(s / 60) % 60)}:${pad(s % 60)}:${pad(f)}`;
}

// Short duration label for cards: 0:22, 3:22
export function shortDur(seconds) {
  const s = Math.round(seconds);
  return `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;
}
